apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs-template-deployment
  annotations:
    iam.amazonaws.com/role: kube_template_role
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: nodejs-template
      labels:
        app: nodejs-template
        tier: web
    spec:
      containers:
      - name: nodejs-template
        image: 077077460384.dkr.ecr.ap-southeast-2.amazonaws.com/nodejs-template
        ports:
        - containerPort: 3000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-template
  labels:
    app: nodejs-template
    tier: web
spec:
  type: NodePort
  selector:
    app: nodejs-template
    tier: web
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nodejs-template-node
spec:
  rules:
  - host: nodejs-template.dev.k8sinternal.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nodejs-template
          servicePort: 80    